name: GitHub Secrets Demo

on:
  push:

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Secret Exists
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is NOT set"
          fi

      - name: Attempt to print secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run: echo "$MY_SECRET"
